import { useEffect, useState } from 'react';
import { Activity, Play, RefreshCw, Square } from 'lucide-react';
import { apiFetch } from '../api';

export default function MonitoringPanel(){
  const [form,setForm]=useState({username:'',password:'',imap_server:'imap.gmail.com',folder:'INBOX',interval:20});
  const [status,setStatus]=useState({running:false,processed:0}); const [alerts,setAlerts]=useState([]); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
  const refresh=async()=>{try{const s=await (await apiFetch('/monitor/status')).json();const a=await (await apiFetch('/alerts')).json();setStatus(s||{});setAlerts(Array.isArray(a)?a:a?.alerts||[]);setError('')}catch(e){setError(e.message||'Monitoring service unavailable.')}};
  // Poll the backend so the live-monitor status and alert feed stay current.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{refresh();const id=setInterval(refresh,5000);return()=>clearInterval(id)},[]);
  const start=async()=>{setLoading(true);setError('');try{const fd=new FormData();Object.entries(form).forEach(([k,v])=>fd.append(k,v));await apiFetch('/monitor/start',{method:'POST',body:fd});await refresh()}catch(e){setError(e.message||'Unable to start mailbox monitoring.')}finally{setLoading(false)}};
  const stop=async()=>{setLoading(true);try{await apiFetch('/monitor/stop',{method:'POST'});await refresh()}catch(e){setError(e.message||'Unable to stop mailbox monitoring.')}finally{setLoading(false)}};
  return <section className="tn-monitor-shell"><div className="tn-card tn-monitor-card"><div className="tn-page-heading"><div><h2><Activity style={{display:'inline',width:17,verticalAlign:'-3px',marginRight:7}}/>Live Mailbox Monitor</h2><p>Optional automated ingestion path: unseen IMAP messages are sent through the same forensic pipeline and can create high-risk cases before manual interaction.</p></div><span className={`tn-monitor-status ${status.running?'running':'stopped'}`}>{status.running?'MONITORING':'STOPPED'}</span></div><div className="tn-monitor-form">{[['username','Mailbox username'],['password','App password'],['imap_server','IMAP server'],['folder','Folder'],['interval','Poll seconds']].map(([key,label])=><label key={key}>{label}<input type={key==='password'?'password':'text'} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div>{error&&<div className="tn-monitor-error">{error}</div>}<div className="tn-monitor-actions"><button className="primary" disabled={loading||status.running} onClick={start}><Play/> Start monitor</button><button disabled={loading||!status.running} onClick={stop}><Square/> Stop</button><button onClick={refresh}><RefreshCw/></button></div><div className="tn-meta-line">Automatically processed: {status.processed||0}{status.last_error?` · Last error: ${status.last_error}`:''}</div><div className="tn-alert-list"><h3>High-risk alerts · {alerts.length}</h3>{alerts.slice(0,8).map((a,i)=><div className="tn-alert-row" key={a.case_id||i}><span>{a.subject||a.sender_email||a.case_id||'High-risk case'}</span><strong>{a.risk_score??'—'}</strong></div>)}{!alerts.length&&<div className="tn-meta-line">No high-risk alerts returned.</div>}</div></div></section>;
}
